SELECT 
	RH.*, 
	CAST(DATE_DEMI_J AS DATE) AS DATE_J
FROM 
	(
		SELECT 
			* 
		FROM 
			TJEPRV_DAOE_PROD.REF_STRUCT 
		WHERE 
			REF_STRUCT.DATE_FIN_VAL = '9999-12-31'
	) REF_STRUCT
	LEFT JOIN TJEPRV_DAOE_PROD.FACT_HISTO_EMPLOYE EMPLOYE ON REF_STRUCT.ID_STR_NIV2 = EMPLOYE.ID_STR
	LEFT JOIN TJEPRV_RH.FACT_OLGA RH ON RH.ID_AGENT = EMPLOYE.ID_EMPLOYE AND RH.DATE_DEMI_J = EMPLOYE.ID_JOUR
	LEFT JOIN TJEPRV_DAOE_PROD.REF_TEMPS REF_TEMPS ON REF_TEMPS.ID_JOUR =  RH.DATE_DEMI_J
WHERE 
	NUMJS NOT IN ('6', '7')
	AND TYPE_PRESENCE = 'P' 
	AND LIB_MOTIF NOT IN ('Télétravail domicile', 'Déplacement', 'Formation en alternance', 'Travail délocalisé agence')
	AND (LIB_STR_NIV5 NOT IN ('POLE CI', 'POLE EI') OR ID_STR_NIV0 IN ('00498', '00600', '00622', '00145'))
GROUP BY 1,2,3,4,5,6,7,8
ORDER BY 8,1,2