CREATE TABLE TJEPRV_DAOE_PROD.FACT_PRESENCE_OLGA AS

SELECT

  A.ID_AGENT,

  C.LIB_AGENT,

  MET.LIB_METIER_NIV1,

  MET.LIB_METIER,

  EMP.ID_STR,

  D.LIB_STR_NIV0,

  D.LIB_STR_NIV2,

  Sum(0.5) PRESENCE_THEO,

  Sum(CASE WHEN A.TYPE_PRESENCE = 'A' OR A.LIB_MOTIF IN ('Réunion Commission Formation','Déplacement','Réunion Commission Marché','Réunion CSE','Réunion CSSCT','Formation','Heures Supplémentaires Récupérables','Réunion commission CIE') THEN 0 ELSE 0.5 END ) PRESENCE_REELLE,

  B.ID_SEM_COMM,

  --A.DATE_DEMI_J,

  CASE WHEN MET.LIB_METIER_NIV1 = 'DA' AND D.LIB_STR_NIV2 LIKE 'MULTI%' THEN 'DA MULTI-SITE'

       WHEN MET.LIB_METIER_NIV1 = 'DA' AND D.LIB_STR_NIV2 IN ('HEM','MARLY','CHAUNY','HESDIN','NOEUX LES MINES','DOUAI SUZANNE LANOY','BERGUES','GRAVELINES','CROIX','RETHEL') THEN 'DA SANS CPRO'

       WHEN MET.LIB_METIER_NIV1 = 'DA' AND D.LIB_STR_NIV2 NOT LIKE 'MULTI%' AND D.LIB_STR_NIV2 NOT IN ('HEM','MARLY','CHAUNY','HESDIN','NOEUX LES MINES','DOUAI SUZANNE LANOY','BERGUES','GRAVELINES','CROIX','RETHEL') THEN 'DA AVEC CPRO'

       ELSE MET.LIB_METIER_NIV1

  END PROFIL,

  Max(B.ID_JOUR) AS DER_JOUR_SEM

FROM

 TJEPRV_RH.FACT_OLGA A

  LEFT JOIN TJEPRV_DAOE_PROD.REF_TEMPS B ON To_Char(B.ID_JOUR, 'YYYYMMDD') = To_Char(A.DATE_DEMI_J, 'YYYYMMDD') 

  LEFT JOIN TJEPRV_DAOE_PROD.FACT_HISTO_EMPLOYE EMP ON To_Char(EMP.ID_JOUR,'YYYYMMDD')=To_Char(A.DATE_DEMI_J, 'YYYYMMDD')  AND EMP.ID_EMPLOYE=A.ID_AGENT

  LEFT JOIN TJEPRV_DAOE_PROD.REF_METIER MET ON EMP.ID_METIER=MET.ID_METIER

  LEFT JOIN TJEPRV_DAOE_PROD.REF_EMPLOYE C ON C.ID_AGENT = A.ID_AGENT

  LEFT JOIN (SELECT * FROM TJEPRV_DAOE_PROD.REF_STRUCT WHERE DATE_FIN_VAL = '9999-12-31') D ON D.ID_STR_NIV0 = EMP.ID_STR

WHERE

  B.LIB_JOUR || To_Char(A.DATE_DEMI_J, 'HH') NOT IN ('Dimanche08','Dimanche02','Samedi02','Lundi08','Lundi02')

  AND MET.LIB_METIER_NIV1 IN ('DA','CPART','CPRO','CPREM')

  --AND A.ID_AGENT = '3594695'

  AND B.ANNEE_COUR = '0'

  AND B.ID_JOUR <= '2023-12-29'

  AND B.SEM_COUR_COMM <= '2'
