name: API Model FastAPI continuous deployment workflow.

on:
  push:
    branches:
      - main  
    paths:
      - 'api_model/**'
      - '.github/workflows/api_model_continuous_deployment.yaml'

jobs:
  health-check-job:
    uses: ./.github/workflows/api_model_continuous_integration.yaml
    secrets: inherit

  build-and-deploy:
    needs: [health-check-job]
    uses: ./.github/workflows/api_model_deployment.yaml
    with:
        app_name: optimeal_model
    secrets: inherit
    
#commen